#!/bin/bash
source /vagrant/environment $VM_MACHINE
_leaf=$(basename $0)

  echo "BEGIN build-vm/$_leaf"

  ### TODO remove any previously installed Docker
  # yum -y remove docker-engine
  # rm -rf /var/lib/docker

  ### Ref https://docs.docker.com/engine/installation/linux/centos/
  yum install -y yum-utils
  yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
  yum makecache fast
  
  ###TODO yum list docker-engine.x86_64  --showduplicates | sort -r
  echo "INSTALLING docker-engine $DOCKER_VERSION (build-vm/$_leaf)"
  yum -y install docker-engine $DOCKER_VERSION
  docker --version

  ### Ref https://docs.docker.com/engine/installation/linux/linux-postinstall/#/manage-docker-as-a-non-root-user
  groupadd docker 2>/dev/null
  usermod -aG docker $USER

  service docker start
  systemctl enable docker

  ### TODO? https://docs.docker.com/engine/installation/linux/linux-postinstall/#/specify-dns-servers-for-docker
  ### TODO? https://docs.docker.com/engine/installation/linux/linux-postinstall/#/allow-access-to-the-remote-api-through-a-firewall
  
  ### Ref https://docs.docker.com/compose/install/
  echo "INSTALLING docker-compose $DOCKER_COMPOSE_VERSION (build-vm/$_leaf)"
  curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  ### Ref https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-centos-7
  yum -y upgrade python*
  curl -L https://raw.githubusercontent.com/docker/compose/${DOCKER_COMPOSE_VERSION}/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
  docker-compose --version

  ln -sf /home/vagrant/docker-compose.yml    /root/docker-compose.yml
  ln -sf /home/vagrant/docker-compose.ci.yml /root/docker-compose.ci.yml

  ### Ref https://github.com/kevana/ui-for-docker
  ###     http://linoxide.com/linux-how-to/setup-dockerui-web-interface-docker/
  ### is in docker-compose already - docker run -d -p 9000:9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock uifd/ui-for-docker

  cat >> /etc/profile.d/00_vagrant_environment.sh << BASHRC_INIT
export DETERDEVOPSTRYOUT_BUILDVM_DOCKER_DONE='$(echo DONE `date`)'
BASHRC_INIT

  echo "END build-vm/$_leaf"
