#!/bin/bash
source /vagrant/environment $VM_MACHINE
_leaf=$(basename $0)

  PYTHON_LATEST=3.4.6 # 3.5.2 not easily available for CentOS7
  [ -n "$1" ] && export PYTHON_VERSION=$1 && shift
  export NUITKA_VERSION=0.5.25-5

  ### Ref https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7
  [ "x$PYTHON_VERSION" = "xLATEST" ] && export PYTHON_VERSION=$PYTHON_LATEST
  [ -z "$PYTHON_VERSION" ] && export PYTHON_VERSION=$PYTHON_LATEST
  echo "BEGIN build-vm/$_leaf ${PYTHON_VERSION}"
  
  yum -y install https://centos7.iuscommunity.org/ius-release.rpm
  source /etc/profile.d/50_vagrant_environment.sh ; set_maj_min $PYTHON_VERSION
  yum -y install python${MAJMIN}u-${PYTHON_VERSION}
  python${MAJ} -V

  ### Ref https://sourcecontribute.com/2015/05/02/compiling-python-to-standalone-executables-on-linux-using-nuitka/
  http://download.opensuse.org/repositories/home:/kayhayen/RedHat_RHEL-7/noarch/nuitka-${NUITKA_VERSION}.1.noarch.rpm
  wget -O /etc/yum.repos.d/kayhayen.repo http://download.opensuse.org/repositories/home:/kayhayen/RedHat_RHEL-7/home:kayhayen.repo
  yum -y install nuitka
  echo "Nuitka version "$(nuitka --version)

  cat >> /etc/profile.d/00_vagrant_environment.sh << BASHRC_INIT
export PYTHON_VERSION=${PYTHON_VERSION}
export NUITKA_VERSION=${NUITKA_VERSION}
export BUILDVM_INSTALLPYTHON_DONE='$(echo DONE $PYTHON_VERSION `date`)'
BASHRC_INIT

  echo "END build-vm/$_leaf" ; echo
