#!/bin/bash
_leaf=$(basename $0)

### Ref https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7
###
### DOCUMENT ROOT:  /usr/share/nginx/html
### DEFAULT CONFIG: /etc/nginx/conf.d/default.conf
### SERVER CONFIGS: /etc/nginx/conf.d
### NGINX CONFIG:   /etc/nginx/nginx.conf

  echo "BEGIN build-vm/$_leaf"

  yum install epel-release
  yum -y install nginx | grep -v "'$CLEANUP_YUM_STDOUT'"
  export NGINX_VERSION=$(nginx -v 2>&1 | cut -f2 -d'/')
  systemctl start nginx
  systemctl enable nginx

  firewall-cmd --permanent --zone=public --add-service=http 
  firewall-cmd --permanent --zone=public --add-service=https
  firewall-cmd --reload

  cat >> /etc/profile.d/00_vagrant_environment.sh << BASHRC_INIT
NGINX_VERSION=$NGINX_VERSION
export BUILDVM_INSTALLNGINX_DONE='$(echo DONE $NGINX_VERSION `date`)'
BASHRC_INIT

  echo "END build-vm/$_leaf" ; echo
