#!/bin/bash
_leaf=$(basename $0)

  echo "BEGIN build-vm/$_leaf"

  echo ' '
  echo "DOCKER:  "`docker --version | sed 's/Docker version //' | cut -f1 -d','`
  echo "COMPOSE: "`docker-compose --version | sed 's/docker-compose version //' | cut -f1 -d','`
  echo "JENKINS: "`java -jar /usr/lib/jenkins/jenkins.war --version`
  echo "NGINX:   $(nginx -v 2>&1 | cut -f2 -d'/')"
  echo "MONIT:   $(monit --version | grep 'Monit version' | sed 's/This is Monit version //')"
  echo "MUNIN:   $(munin-node --version | grep munin-node | cut -f2 -d'v')"

  echo ' '
  echo "JAVA:    $(java -version 2>&1 | grep 'openjdk version' | cut -f2 -d'"')"
  source /etc/profile.d/50_vagrant_environment.sh ; set_maj_min $PYTHON_VERSION
  echo "PYTHON${MAJ}: "$(python${MAJ} -V 2>&1 | sed 's/Python //')
  echo "PYTHON:  "$(python -V 2>&1 | sed 's/Python //')
  echo "NUITKA:  "$(nuitka --version)
  echo "RUBY:    "$(ruby --version | sed 's/ruby //' | cut -f1 -d'p')
  echo "GO:      "$(go version | sed 's/go version go//' | cut -f1 -d' ')
  echo "COFFEE:  "$(coffee --version | sed 's/CoffeeScript version //')
  echo "GIT:     "$(git --version | sed 's/git version //')

  _LOCAL_IP=`ip addr show | grep inet | grep -v inet6 | grep -v 10.0.2 | grep /24 | sed 's/.*inet\s*//' | cut -f1 -d'/'`
  echo ' ' ; echo "HOSTNAME=`hostname` VM_IP_ADDR=$_LOCAL_IP VM_PORT_PREFIX=$VM_PORT_PREFIX"

  echo "export BUILDVM_VERIFY_DONE='$(echo DONE `date`)'" >> /etc/profile.d/99_vagrant_environment.sh

  echo ' ' ; echo "END build-vm/$_leaf"
